FROM node:22.17.1

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

ARG TZ
ENV TZ=$TZ

ARG DOMAIN_NAME
ENV VITE_DOMAIN_NAME=$DOMAIN_NAME

WORKDIR /app/
COPY ./frontend/ /app/
RUN npm install
RUN npm run build
CMD ["npm", "run", "preview"]
