name: Release 0.3.1x

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-031x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 0.3.1x
        uses: actions/checkout@v4
        with:
          ref: 0.3.1x
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Compute next numeric tag for 0.3.1x
        id: version
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="0.3.1x"
          # Find latest numeric suffix for tags like 0.3.1x-<N>
          LAST_NUM=$(
            git tag -l "${BRANCH}-*" \
            | sed -n "s/^${BRANCH}-\([0-9]\+\)$/\1/p" \
            | sort -n | tail -1
          )
          if [[ -z "${LAST_NUM:-}" ]]; then
            NEXT=1
            RANGE="HEAD"
          else
            NEXT=$((LAST_NUM + 1))
            RANGE="${BRANCH}-${LAST_NUM}..HEAD"
          fi
          NEW_TAG="${BRANCH}-${NEXT}"
          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
          echo "range=${RANGE}" >> "$GITHUB_OUTPUT"

      - name: Generate release notes (subject, short SHA, author, link)
        id: notes
        shell: bash
        run: |
          set -euo pipefail
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          RANGE="${{ steps.version.outputs.range }}"
          git log --no-merges --pretty=format:"- %s (%h) by %an → ${REPO_URL}/commit/%H" ${RANGE} > notes.md || true
          [[ -s notes.md ]] || echo "No changes (empty range)." > notes.md
          echo "notes_path=notes.md" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          target_commitish: 0.3.1x
          name: ${{ steps.version.outputs.new_tag }}
          body_path: ${{ steps.notes.outputs.notes_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
