name: Release 0.3.1x

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-031x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 0.3.1x
        uses: actions/checkout@v4
        with:
          ref: 0.3.1x
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Compute next version tag (per-branch)
        id: version
        shell: bash
        run: |
          set -euo pipefail
          VERSION_PREFIX="v"
          LAST=$(git tag --list "${VERSION_PREFIX}[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n1 || true)
          if [[ -z "${LAST}" ]]; then
            NEW="${VERSION_PREFIX}1.0.0"
            RANGE="HEAD"
          else
            V=${LAST#${VERSION_PREFIX}}
            IFS='.' read -r MA MI PA <<<"$V"
            PA=$((PA+1))
            NEW="${VERSION_PREFIX}${MA}.${MI}.${PA}"
            RANGE="${LAST}..HEAD"
          fi
          echo "new_tag=${NEW}" >> "$GITHUB_OUTPUT"
          echo "range=${RANGE}" >> "$GITHUB_OUTPUT"

      - name: Generate release notes (subject, short SHA, author, link)
        id: notes
        shell: bash
        run: |
          set -euo pipefail
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          RANGE="${{ steps.version.outputs.range }}"
          git log --no-merges --pretty=format:"- %s - by %an → ${REPO_URL}/commit/%H" ${RANGE} > notes.md || true
          [[ -s notes.md ]] || echo "No changes (empty range)." > notes.md
          echo "notes_path=notes.md" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          target_commitish: 0.3.1x
          name: Release ${{ steps.version.outputs.new_tag }}
          body_path: ${{ steps.notes.outputs.notes_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}